### ISSUE TITLE
Would love to know if your team would consider open sourcing your converter?

### ISSUE THREAD

**Issue by zeluspudding** [NativeDocuments/docx-wasm-client-side#4]
Seems unlikely to get anyone from NativeDocuments attention on this but it seemed like you had a really promising tool here - so sad to see it go. We'd all hate to see this project disappear if the progress that had been made could be respun as an opensource solution that saves dev folks time (and money). Any chance the internet community could receive this beauty? For example, the [fuzzy.ai team opensourced ](https://web.archive.org/web/20190903115047/https://fuzzy.ai/)their technology after their company ended ([its on gitlab](https://gitlab.com/fuzzy-ai)). I'm sure there are many who would find this useful.

**Comment by calebjclark** [comment]
+1

**Comment by gexcube** [comment]
+1

**Comment by garylyn** [comment]
Hi pudding,

Thanks for the kind comments but docX-wasm is no longer available.  The docX library will not be open-sourced but don't let that stop you from creating your own world-changing open-source project.   Amazing things are possible.  At the heart of docX-wasm is some very special magic based on years of research, years of disappointing experiences, decades of self-made expertise, dedicated professional involvement, a persistent determination against all odds and opinions, and the hard work of endless trial and error.

But hey, it can be done!  At the heart of every successful open-source project are people who look to solve on their own the problems they encounter.  They believe in themselves.  They are self-determined.  This self-reliance and personal determination are what attracts others to contribute.  The self-reliance and determination of a few becomes the self-reliance and determination of a community.  Looking to the hard work and determination of someone else to solve your problems is not a good start for an open-source project.  Just my opinion.  But I hope you think about that.

The developer of docX-wasm has solved one of the most difficult problems known to the document processing world.  That is;  how to unlock complex WORD documents from the originating application(s), processing these docs to make them accessible to many different next-generation applications and services; where analysis, repurposing, collaboration, and roundtripping back into existing workflows and information systems is essential.

The developer of docX-wasm is currently working on a new product that recently entered closed beta.    The new product is a document processing and augmented collaboration framework for the training and commercial production of emerging AI/NLP systems.   

Many thanks to all those who appreciated docX-wasm.  When the new product is available for local client installation an announcement will be posted.  If you liked docX-wasm, the new product will blow you away.  

Native Documents will not be handling the new product but will continue servicing existing obligations. 

gary.edwards@nativedocuments.com

**Comment by zeluspudding** [comment]
Yes, there is absolutely no reason this should be an open source project if you can make money with it. Unlocking WORD documents from MS Word **is** a hard nut to crack, as you say, and having struggled to build applications myself, I feel the weight of every word of that. As such, DocX-wasm ought to generate a lot of revenue.

My only point was that Fuzzy.ai, which went bankrupt, has sweat and tears baked into it - and it's creators recognized that it would have been somewhat wasted sweat and tears to purposefully drawer that work - no one to get value from it ever again. That's [why they open sourced it](https://mailchi.mp/924d13343159/fuzzyai-api-service-to-end-on-december-31-2018?e=64d00bcecc)

Parse.com, which was bought and then folded by Facebook, has sweat and tears baked into it - and its creators recognized that it would have been somewhat wasted sweat and tears to purposefully drawer that work. [That's why they open sourced it](https://blog.parseplatform.org/announcements/what-is-parse-server/)

[Bubble](https://bubble.io), which is just a mind blowing piece of software, has many hours of sweat and mind racking frustration baked into it. That's at least partially why, if Bubble is ever to go out of business, [the founder has promised to open source its code base](https://forum.bubble.io/t/migration-of-code-data-out-of-bubble/1126/2?u=zelus_pudding)

The messaging that people who find docX-wasm see is this:

> "We no longer exist... our product is dead. It is totally unclear if this will ever be worked on again or if its founders are even alive."

@JasonHarrop is a very smart man who deserves to get rich off of this application. I hope he does. I think all that anyone here wanted was to maybe see a "Were closed for good", or a "We'll be back in 5 minutes" sign hanging in the window. So thank you for hanging it up :)

I would love to know when that new service goes live. I don't believe I'm on any of your mailing lists so please respond back here if you can :) All the best team!

**Comment by garylyn** [comment]
Hi Pudding,

Thanks for the kind response.  I will make certain notice is posted here. and will personally contact you.  OBTW, Jason is not the developer of the docX-JavaScript-docX/PDF library.  That honor belongs soley and entirely to Florian Reuter. You are going to be blown away by his new work.  I am hoping for a docXai-electron in six months or less.  No promises but fingers crossed.

**Comment by AcidRaZor** [comment]
Seems nativedocuments.com has entirely folded, and I think their short-sighted (read: dick move) to not open source this and provide value to the community at large is a big FU to anyone in this field. If you're a dev or run a small startup that solves a problem like this and you find this note. Don't be a dick if you fail and no longer profit off of your work. Share it so others who find it useful can expand and keep your work alive
